/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAOs.DAOEmprestimo2;
import DAOs.DAOExemplar2;
import DAOs.DAOLivro2;
import DAOs.DAOUsuario2;
import Entidades.Emprestimo;
import Entidades.Exemplar;
import Entidades.Funcionario;
import Entidades.Livro;
import Entidades.Usuario;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;
/**
 *
 * @author T-Gamer
 */
public class PermiteEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form PermiteEmprestimo
     */
    public PermiteEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idexemplar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idfuncionario = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tusuario = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tlivro = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Para Realizar Emprestimo"));

        jLabel1.setText("MATRICULA");

        jLabel2.setText("IDEXEMPLAR");

        jButton1.setText("Exibir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exibir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("IDFUNCIONARIO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idexemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idexemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Usuário"));

        Tusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "SEXO", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(Tusuario);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Livro"));

        Tlivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TITULO", "AUTOR", "ANO", " Num DISPONIVEIS"
            }
        ));
        jScrollPane2.setViewportView(Tlivro);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jButton3.setText("Permitir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // entidades:
        Usuario usu=new Usuario();
        Livro liv = new Livro();
        Exemplar exem = new Exemplar();
        Funcionario f= new Funcionario();        
        Emprestimo emp =new Emprestimo();        
        //classes para trabalhar com datas:
        Calendar cal =Calendar.getInstance();        
        SimpleDateFormat adf = new SimpleDateFormat("yyyy/MM/dd");//formato que eu uero usar     
        Calendar cal2 =Calendar.getInstance();
        cal2.add(Calendar.MONTH, 1);//um mes dps da data atual
        //setando os valores da interface       
        usu.setIdusuario(idusuario.getText());
        int ide=Integer.parseInt(idexemplar.getText());
        exem.setIdexemplar(ide);
        f.setIdfuncionario(idfuncionario.getText());
        
        DAOLivro2 daol = new DAOLivro2();
        int total=0;
        try {
            if(verificaUsuario(usu)==true && verificalivro(exem,liv)==true){
                //o livro e usuario existem e setamos o idlivro para liv//
                total=liv.getTotexemplares();
                if(total>0){//se tenho exemplares disponiveis//                    
                    
                  //METODO DE CADASTRAR EMPRESTIMO//
                  emp.setIdexemplar(ide);
                  emp.setIdfuncionario(idfuncionario.getText());
                  emp.setDataD(adf.format(cal2.getTime()));
                  emp.setDataE(adf.format(cal.getTime()));
                  emp.setIdusuario(usu.getIdusuario());
                                                      
                  //efetuo o emprestimo
                  DAOEmprestimo2 cad = new DAOEmprestimo2();
                  cad.inserir(emp);
                  
                  //imprimir comprovante de emprestimo//
                  comprovanteEmprestimo(emp);
                                    
                 //ja que o emprestimo foi permitido, atualizo o numero de exemplares disponiveis na entidade LIVRO//
                  daol.updateExemDisp(liv);
                  
                   JOptionPane.showMessageDialog(null, "Emprestimo Permitido!");
                }
                
            }else{
                 JOptionPane.showMessageDialog(null, "Usuário ou Livro não encontrados!");
                
            }} catch (SQLException ex) {
            Logger.getLogger(PermiteEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PermiteEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
      
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Usuario novo=new Usuario();
        String mat=idusuario.getText();
        novo.setIdusuario(mat);
        DAOUsuario2 daou = new DAOUsuario2();
        try {
            if(daou.getDados(novo)==true){
               DefaultTableModel usu = (DefaultTableModel)Tusuario.getModel();
               daou.getDados(novo);
               Object[] dados= {novo.getUnome(),novo.getUcpf(),novo.getSexo(),novo.getTel()};
               usu.addRow(dados);
               
                         
            }else{
                 JOptionPane.showMessageDialog(null, "usuario não encontrado!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(buscaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // exibir o livro que quero emprestar:
        Livro liv = new Livro();
        Exemplar exem = new Exemplar();
        verificalivro(exem,liv);
        
        DAOLivro2 daou = new DAOLivro2();
        try {
            if(daou.getDados(liv)==true){
               DefaultTableModel usu = (DefaultTableModel)Tlivro.getModel();
               daou.getDados(liv);
               Object[] dados= {liv.getTitulo(),liv.getAutor(),liv.getAno(),liv.getExemplaresdisp()};
               usu.addRow(dados);
                             
            }else{
                 JOptionPane.showMessageDialog(null, "Livro não encontrado!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(buscaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public boolean verificalivro(Exemplar exe, Livro l){
        DAOExemplar2 daoe = new DAOExemplar2();
        int aux=Integer.parseInt(idexemplar.getText());
        exe.setIdexemplar(aux);
         try {
            if(daoe.getDados(exe)==true){
                l.setIdlivro(exe.getIdlivro());
                
                //pegando a quantidade de exemplares disponiveis//
                DAOLivro2 daol = new DAOLivro2();
                 if(daol.getDados(l)==true){
                   l.setExemplaresdisp(l.getExemplaresdisp());
                 }
                
                return true;
                
            }else{
                JOptionPane.showMessageDialog(null, "Livro não encontrado!");
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(PermiteEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
      return false;
     
    }
    
    public boolean verificaUsuario(Usuario u) throws SQLException{
      DAOUsuario2 daou = new DAOUsuario2();
      u.setIdusuario(idusuario.getText());
       if(daou.getDados(u)==true){
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                return false;
            }
    }

    public void comprovanteEmprestimo(Emprestimo em) throws IOException, SQLException{
        DAOEmprestimo2 cad = new DAOEmprestimo2();
        Emprestimo emp= new Emprestimo();
        emp=cad.getDadosParaDev(em);
        String idem= Integer.toString(emp.getIdemprestimo());
        String idex= Integer.toString(emp.getIdexemplar());
        
       Path caminho = Paths.get("C:/Users/T-Gamer/Desktop/Emprestimos/Emprestimo.txt");
       String emprestimo="------Comprovante de Emprestimo--------\n1-IDEMPRESTIMO "+idem+"\n"+
               "DATA DA DEVOLUÇÃO "+em.getDataD()+"\n"+
               "IDUSUARIO "+em.getIdusuario()+"\n"+
               "IDEXEMPLAR "+idex;
       byte[] txtembyte = emprestimo.getBytes();
       Files.write(caminho, txtembyte);
      
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tlivro;
    private javax.swing.JTable Tusuario;
    private javax.swing.JTextField idexemplar;
    private javax.swing.JTextField idfuncionario;
    private javax.swing.JTextField idusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

  
}
