/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import DAOs.DAODevolucao;
import DAOs.DAOEmprestimo2;
import DAOs.DAOExemplar2;
import DAOs.DAOLivro2;
import DAOs.DAOUsuario2;
import Entidades.Devoluçao;
import Entidades.Emprestimo;
import Entidades.Exemplar;
import Entidades.Livro;
import Entidades.Usuario;
import java.io.IOException;
import static java.lang.Math.random;
import static java.lang.StrictMath.random;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Period;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author T-Gamer
 */
public class ReceberEmprestimo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ReceberEmprestimo
     */
    public ReceberEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idexemplar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idfuncionario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tusuario = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tlivro = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setClosable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados para Receber Emprestimo"));

        jLabel1.setText("MATRICULA");

        jLabel2.setText("IDEXEMPLAR");

        jLabel3.setText("IDFUNCIONARIO");

        jButton1.setText("Exibir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exibir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(idusuario)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idexemplar)
                    .addComponent(idfuncionario))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idexemplar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Usuario"));

        Tusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CPF", "SEXO", "TELEFONE"
            }
        ));
        jScrollPane1.setViewportView(Tusuario);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Livro"));

        Tlivro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TITULO", "AUTOR", "LIVRO", "Num DISPONIVEIS"
            }
        ));
        jScrollPane2.setViewportView(Tlivro);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jButton3.setText("Receber");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jButton3)
                .addGap(181, 181, 181))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // RECEBER UM EMPRESTIMO(DEVOLUÇAO):
        Emprestimo em = new Emprestimo();
        DAOEmprestimo2 daoe = new DAOEmprestimo2();
        Devoluçao de = new Devoluçao();
        DAODevolucao daod = new DAODevolucao();
        
        em.setIdusuario(idusuario.getText());
        int ide = Integer.parseInt(idexemplar.getText());
        em.setIdexemplar(ide);
        em.setIdfuncionario(idfuncionario.getText());
        
        Calendar cal =Calendar.getInstance();        
        SimpleDateFormat adf = new SimpleDateFormat("yyyy-MM-dd");//formato que eu quero usar             
        String atual=adf.format(cal.getTime());//pega data atual
        String entrega=null;// vai guardar a data que devia ser entregue
        
        float valmulta=0;//vai guardar o valor da multa no caso de atraso
        
        try {
            
            daoe.getDadosParaDev(em);// pega os dados do emprestimo para anilisar a devolucao atraves do idexemplar,idfuncionario e idusuario que foram setados acima// 
            if(daoe.getDados(em)==true){
                entrega=em.getDataD();
                if(atual.compareTo(entrega)>0){ 
                    de.setDatad(em.getDataD());
                    de.setAtrasado("1");
                    
                    valmulta=(float) (daod.calculaTempAtraso(entrega)*0.59);//0.59 por dia de atraso na devolucao de um exenplar
                    de.setValormulta(valmulta);
                    
                    de.setValormulta(valmulta);
                    de.setIdemprestimo(em.getIdemprestimo());
                    de.setIdusuario(idusuario.getText());
                    de.setIdfuncionario(idfuncionario.getText());
                    de.setIdexemplar(ide);
                    daod.inserir(de);
                    
                    //comprovante
                    comprovanteDevolucao(de);
                    
                    //exclui o emprestimo, ja que ele foi devolvido
                    daoe.excluir(em);
                    
                    JOptionPane.showMessageDialog(null, "Devoluçao fora do prazo!");
                }else{
                    de.setDatad(em.getDataD());
                    de.setAtrasado("0");
                    de.setValormulta(0);
                    de.setIdemprestimo(em.getIdemprestimo());
                    de.setIdusuario(idusuario.getText());
                    de.setIdfuncionario(idfuncionario.getText());
                    de.setIdexemplar(ide);
                    daod.inserir(de);                  
                                      
                    //comprovante
                    comprovanteDevolucao(de);
                    
                     //exclui o emprestimo, ja que ele foi devolvido
                    daoe.excluir(em);
                    
                    JOptionPane.showMessageDialog(null, "Devolução em dia");
                    
                }
                
            }else{               
              JOptionPane.showMessageDialog(null, "Emprestimo não encontrado!");
            }
  
            
        } catch (SQLException ex) {
            Logger.getLogger(ReceberEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ReceberEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }       
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Usuario novo=new Usuario();
        String mat=idusuario.getText();
        novo.setIdusuario(mat);
        DAOUsuario2 daou = new DAOUsuario2();
        try {
            if(daou.getDados(novo)==true){
               DefaultTableModel usu = (DefaultTableModel)Tusuario.getModel();
               daou.getDados(novo);
               Object[] dados= {novo.getUnome(),novo.getUcpf(),novo.getSexo(),novo.getTel()};
               usu.addRow(dados);
               
                         
            }else{
                 JOptionPane.showMessageDialog(null, "usuario não encontrado!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(buscaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Livro liv = new Livro();
        Exemplar exem = new Exemplar();
        verificalivro(exem,liv);
        
        DAOLivro2 daou = new DAOLivro2();
        try {
            if(daou.getDados(liv)==true){
               DefaultTableModel usu = (DefaultTableModel)Tlivro.getModel();
               daou.getDados(liv);
               Object[] dados= {liv.getTitulo(),liv.getAutor(),liv.getAno(),liv.getExemplaresdisp()};
               usu.addRow(dados);
                             
            }else{
                 JOptionPane.showMessageDialog(null, "Livro não encontrado!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(buscaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
      public boolean verificalivro(Exemplar exe, Livro l){
        DAOExemplar2 daoe = new DAOExemplar2();
        int aux=Integer.parseInt(idexemplar.getText());
        exe.setIdexemplar(aux);
         try {
            if(daoe.getDados(exe)==true){
                l.setIdlivro(exe.getIdlivro());
                
                //pegando a quantidade de exemplares disponiveis//
                DAOLivro2 daol = new DAOLivro2();
                 if(daol.getDados(l)==true){
                   l.setExemplaresdisp(l.getExemplaresdisp());
                 }
                
                return true;
                
            }else{
                JOptionPane.showMessageDialog(null, "Livro não encontrado!");
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(PermiteEmprestimo.class.getName()).log(Level.SEVERE, null, ex);
        }
      return false;
     
    }
    
    public boolean verificaUsuario(Usuario u) throws SQLException{
      DAOUsuario2 daou = new DAOUsuario2();
      u.setIdusuario(idusuario.getText());
       if(daou.getDados(u)==true){
                return true;
            }else{
                JOptionPane.showMessageDialog(null, "Usuario não encontrado!");
                return false;
            }
    }

    
    public void comprovanteDevolucao(Devoluçao dev) throws IOException{
        String iddev= Integer.toString(dev.getIddevolucao());
        String idex= Integer.toString(dev.getIdexemplar());
        
       Path caminho = Paths.get("C:/Users/T-Gamer/Desktop/Devoluçoes/devolucao.txt");
       String emprestimo="------Comprovante de Devolução--------\n1-IDDEVOLUÇÃO "+iddev+"\n"+
               "DATA DA DEVOLUÇÃO "+dev.getDatad()+"\n"+
               "IDUSUARIO "+dev.getIdusuario()+"\n"+
               "IDEXEMPLAR "+idex+"\n"+
               "MULTA "+dev.getValormulta();
       byte[] txtembyte = emprestimo.getBytes();
       Files.write(caminho, txtembyte);
      
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tlivro;
    private javax.swing.JTable Tusuario;
    private javax.swing.JTextField idexemplar;
    private javax.swing.JTextField idfuncionario;
    private javax.swing.JTextField idusuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
